package net.demomaker.busnetworkgenerator.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class HomePage extends JFrame {
    private static final int WIDTH = 1280;
    private static final int HEIGHT = 720;
    private static final String DEFAULT_TITLE = "Bus Network Generator";
    private static final String TITLE_FORMAT = "%s : %s, %s";
    private JPanel panel1;

    public HomePage() {
        this(DEFAULT_TITLE);
    }

    public HomePage(String title) {
        super(title);
        updateTitle();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(panel1);
        this.pack();
        this.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent componentEvent) {
                // do stuff
                updateTitle();
            }
        });
        this.setSize(WIDTH, HEIGHT);
        createUIComponents();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        final JImagePanel jImagePanel1 = new JImagePanel();
        panel1.add(jImagePanel1, BorderLayout.CENTER);
    }

    private void updateTitle() {
        setTitle(String.format(TITLE_FORMAT, DEFAULT_TITLE, getSize().width, getSize().height));
    }


    public static void main(String[] args) {
        JFrame frame = new HomePage();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new javax.swing.JPanel();
        panel1.setLayout(new java.awt.BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public javax.swing.JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
